<!-- BEGIN_TF_DOCS -->
environment_variables = {}
event_mapping         = {}
handler               = ""
image_uri             = ""
name                  = ""
package_file          = ""
runtime               = ""
source_dir            = ""
source_file           = ""
vpc_config            = ""
<!-- END_TF_DOCS -->